// Datenbasis: 30 aetherische Oele mit gesundheitlichem Schwerpunkt.
// Formulierungen bewusst als traditionelle/erfahrungsheilkundliche Anwendung,
// nicht als Heilversprechen (Heilmittelwerbegesetz).

module.exports = [
  {
    nr: 1, name: "Lavendel", latin: "Lavandula angustifolia", img: "lavendel",
    gruppe: "Blüten", herkunft: "Frankreich (Provence), Bulgarien",
    schwerpunkt: "Schlaf, Unruhe, Hautpflege",
    duft: "blumig-krautig, frisch, leicht süß",
    gewinnung: "Wasserdampfdestillation der Blütenrispen",
    inhalt: "Linalool (25–38 %), Linalylacetat (25–45 %)",
    text: "Lavendel gilt als das Allround-Öl der Aromatherapie und ist für Einsteiger das wichtigste Öl überhaupt. Sein ausgleichender Duft macht ihn zum Klassiker für Entspannung, erholsamen Schlaf und die tägliche Hautpflege.",
    gesundheit: "In der Erfahrungsheilkunde wird Lavendel vor allem mit innerer Ruhe in Verbindung gebracht. Der hohe Anteil an Estern gilt in der Aromapraxis als Grund für den entspannenden Charakter des Öls. Traditionell wird es bei nervöser Unruhe, Einschlafproblemen und Anspannung eingesetzt sowie zur Pflege beanspruchter Haut. Lavendel zählt zu den am besten untersuchten ätherischen Ölen überhaupt.",
    anwendungen: [
      ["Erholsamer Schlaf", "3–4 Tropfen am Abend im Diffusor im Schlafzimmer verströmen, etwa 30 Minuten vor dem Zubettgehen."],
      ["Innere Unruhe", "Einen Tropfen auf ein Taschentuch geben und bei Anspannung bewusst mehrmals tief einatmen."],
      ["Hautpflege", "1–2 Tropfen mit einem Teelöffel Olivenöl verdünnen und punktuell auf unreine oder gereizte Hautstellen auftragen."],
      ["Nach Sonneneinwirkung", "Mit Aloe-Vera-Gel gemischt kühlend auf die beanspruchte Haut auftragen."],
      ["Kopf- und Nackenmassage", "2 Tropfen auf einen Esslöffel Olivenöl geben und Nacken und Schläfen sanft einmassieren."],
      ["Kleine Schürfwunden", "Nach dem Reinigen 1 Tropfen auf einen Teelöffel Olivenöl geben und den Wundrand vorsichtig betupfen – nicht in die offene Wunde."],
      ["Insektenstiche", "1 Tropfen mit Olivenöl verdünnt auf den Stich tupfen, bei Bedarf mehrmals täglich wiederholen."],
    ],
    sicherheit: "In empfohlener Verdünnung sehr gut hautverträglich. Vor der Erstanwendung dennoch einen Patch-Test in der Armbeuge durchführen.",
  },
  {
    nr: 2, name: "Pfefferminze", latin: "Mentha piperita", img: "pfefferminze",
    gruppe: "Kräuter", herkunft: "USA, Frankreich, Deutschland",
    schwerpunkt: "Kopf, Konzentration, Verdauung",
    duft: "frisch, minzig-kühlend, durchdringend",
    gewinnung: "Wasserdampfdestillation des blühenden Krauts",
    inhalt: "Menthol (35–45 %), Menthon (15–25 %)",
    text: "Pfefferminzöl ist bekannt für seinen erfrischenden, belebenden Duft und gehört zu den vielseitigsten Ölen für den Alltag.",
    gesundheit: "Menthol erzeugt auf der Haut einen kühlenden Reiz, der traditionell bei Spannungsgefühlen im Kopf- und Nackenbereich genutzt wird. In der Erfahrungsheilkunde gilt Pfefferminze außerdem als Öl für einen klaren Kopf sowie für ein wohliges Bauchgefühl. Die Anwendung bei Verspannungskopfschmerz durch Einreiben der Schläfen ist eine der bekanntesten Hausanwendungen überhaupt.",
    anwendungen: [
      ["Klarer Kopf", "2 Tropfen im Diffusor am Schreibtisch für konzentriertes Arbeiten verströmen."],
      ["Spannungsgefühl im Kopf", "1 Tropfen auf einen Teelöffel Olivenöl geben und sanft an Schläfen und Nacken einmassieren – Augenkontakt unbedingt vermeiden."],
      ["Wohlgefühl im Bauch", "2 Tropfen auf einen Esslöffel Olivenöl geben und im Uhrzeigersinn auf den Bauch einmassieren."],
      ["Erfrischung an heißen Tagen", "1 Tropfen mit Wasser in einer Sprühflasche als kühlendes Körperspray verwenden, Augenpartie aussparen."],
      ["Müde Beine", "2 Tropfen mit Olivenöl verdünnt von unten nach oben ausstreichen."],
      ["Kopfschmerzen vom Verspannungstyp", "1 Tropfen auf einen Teelöffel Olivenöl geben und Schläfen und Nacken einreiben, Augenpartie aussparen."],
      ["Reiseübelkeit", "Einen Tropfen auf ein Taschentuch geben und bei aufkommender Übelkeit langsam einatmen."],
    ],
    sicherheit: "Nicht bei Kindern unter 6 Jahren, in Schwangerschaft und Stillzeit. Wegen des kühlenden Menthols nie in Augennähe, auf Schleimhäuten oder großflächig anwenden.",
  },
  {
    nr: 3, name: "Teebaum", latin: "Melaleuca alternifolia", img: "teebaum",
    gruppe: "Bäume & Harze", herkunft: "Australien",
    schwerpunkt: "Haut, Fußpflege, Haushalt",
    duft: "krautig-frisch, leicht medizinisch",
    gewinnung: "Wasserdampfdestillation der Blätter und Zweigspitzen",
    inhalt: "Terpinen-4-ol (min. 30 %), γ-Terpinen",
    text: "Teebaumöl ist eines der bekanntesten Öle für Haut und Haushalt und wird seit Generationen von den Aborigines Australiens geschätzt.",
    gesundheit: "Terpinen-4-ol gilt als der zentrale Wirkstoff des Teebaumöls und ist Gegenstand zahlreicher wissenschaftlicher Untersuchungen. In der Hautpflege wird Teebaum traditionell bei unreiner Haut, im Fußbereich und zur Nagelpflege eingesetzt. Im Haushalt dient er als natürliche Alternative in Reinigungsmitteln. Die Qualität steht und fällt mit dem Terpinen-4-ol-Gehalt – achten Sie beim Kauf auf diese Angabe.",
    anwendungen: [
      ["Unreine Haut", "Stark verdünnt (1 Tropfen auf einen Teelöffel Olivenöl) mit einem Wattestäbchen punktuell auftragen."],
      ["Fußpflege", "3–4 Tropfen in ein warmes Fußbad geben für ein frisches, gepflegtes Gefühl."],
      ["Nagelpflege", "1 Tropfen mit Olivenöl verdünnt täglich in den Nagelrand einmassieren."],
      ["Natürlicher Haushaltsreiniger", "10 Tropfen auf 500 ml Wasser in einer Sprühflasche als Oberflächenreiniger."],
      ["Wäschefrische", "3 Tropfen ins Waschmittelfach geben, besonders bei Sport- und Handtuchwäsche."],
      ["Fuß- und Nagelpilz begleitend", "1 Tropfen auf einen Teelöffel Olivenöl geben und zweimal täglich auf die betroffene Stelle auftragen."],
      ["Halsbereich bei Erkältung", "2 Tropfen mit Olivenöl verdünnt äußerlich auf den Hals auftragen – nicht gurgeln, nicht einnehmen."],
    ],
    sicherheit: "Nie unverdünnt großflächig auftragen, kann empfindliche Haut reizen. Oxidiertes (altes) Öl reizt stärker – nach 12 Monaten ersetzen. Nicht in Räumen verdampfen, in denen sich Katzen aufhalten.",
  },
  {
    nr: 4, name: "Eukalyptus", latin: "Eucalyptus globulus", img: "eukalyptus",
    gruppe: "Bäume & Harze", herkunft: "Australien, Spanien, Portugal",
    schwerpunkt: "Atemwege, Erkältungszeit",
    duft: "kühl, kampferartig, durchdringend-frisch",
    gewinnung: "Wasserdampfdestillation der Blätter",
    inhalt: "1,8-Cineol (70–85 %), α-Pinen",
    text: "Eukalyptusöl ist der Klassiker der kalten Jahreszeit und in fast jeder Erkältungssalbe zu finden.",
    gesundheit: "1,8-Cineol ist der bekannteste Vertreter der Oxide und wird traditionell mit freier Atmung in Verbindung gebracht. Eukalyptus gehört deshalb zu den am häufigsten eingesetzten Ölen in der Erkältungszeit – als Dampfbad, Brusteinreibung oder im Diffusor. In der Aromapraxis gilt es zudem als klärendes Öl für Raumluft und Konzentration.",
    anwendungen: [
      ["Erkältungszeit", "2–3 Tropfen im Diffusor im Wohnzimmer verströmen, nicht dauerhaft."],
      ["Dampfbad für Erwachsene", "1–2 Tropfen in eine Schüssel heißes Wasser, Kopf mit Handtuch bedecken und den Dampf mit geschlossenen Augen 5–10 Minuten einatmen."],
      ["Brusteinreibung", "2 Tropfen auf einen Esslöffel Olivenöl geben und sanft auf Brust und oberen Rücken einmassieren."],
      ["Saunaaufguss", "1–2 Tropfen mit dem Aufgusswasser mischen."],
      ["Nach dem Sport", "Mit Pfefferminze kombiniert als kühlendes Massageöl mit Olivenöl verwenden."],
      ["Festsitzender Husten", "2 Tropfen auf einen Esslöffel Olivenöl geben und mehrmals täglich auf die Brust einreiben."],
      ["Verstopfte Nase", "1 Tropfen auf ein Taschentuch geben und in Abständen daran riechen – niemals direkt in die Nase."],
    ],
    sicherheit: "Nicht bei Kindern unter 6 Jahren, nie im Gesicht von Babys und Kleinkindern. Bei Asthma und Epilepsie nur nach ärztlicher Rücksprache.",
  },
  {
    nr: 5, name: "Zitrone", latin: "Citrus limon", img: "zitrone",
    gruppe: "Zitrus", herkunft: "Italien (Sizilien), Spanien",
    schwerpunkt: "Frische, Reinigung, Konzentration",
    duft: "frisch, spritzig, fruchtig-sauer",
    gewinnung: "Kaltpressung der Fruchtschalen",
    inhalt: "Limonen (60–75 %), β-Pinen, γ-Terpinen",
    text: "Zitronenöl wird kaltgepresst aus der Schale gewonnen und gilt als das aufhellende Öl schlechthin – für Stimmung, Raumluft und Reinigung.",
    gesundheit: "Limonen ist das am häufigsten vorkommende Monoterpen in Zitrusölen und wird in der Aromapraxis mit stimmungsaufhellenden und klärenden Eigenschaften verbunden. Traditionell dient Zitronenöl der Raumluftreinigung, der Unterstützung von Konzentration und Frische sowie als natürlicher Bestandteil von Reinigungsmitteln. Wichtig ist die Phototoxizität – nach Hautanwendung Sonne meiden.",
    anwendungen: [
      ["Frischer Start in den Tag", "3 Tropfen im Diffusor für ein belebendes Raumklima am Morgen."],
      ["Konzentration", "Mit Rosmarin kombiniert im Diffusor am Arbeitsplatz verströmen."],
      ["Küchenreiniger", "10 Tropfen auf 500 ml Wasser mit einem Schuss Essig als natürlichen Allzweckreiniger."],
      ["Fett- und Klebstoffreste", "Einen Tropfen direkt auftragen, vorher an unauffälliger Stelle testen."],
      ["Raumluft nach dem Kochen", "3 Tropfen im Diffusor gegen Kochgerüche verströmen."],
      ["Halskratzen in der Erkältungszeit", "3 Tropfen im Diffusor verströmen, um die Raumluft zu klären."],
      ["Übelkeit am Morgen", "Einen Tropfen auf ein Taschentuch geben und langsam tief einatmen."],
    ],
    sicherheit: "Stark phototoxisch – nach Hautkontakt mindestens 12 Stunden direkte Sonne und Solarium meiden. Kaltgepresstes Öl oxidiert schnell, kühl lagern und binnen 12 Monaten verbrauchen.",
  },
  {
    nr: 6, name: "Orange süß", latin: "Citrus sinensis", img: "orange",
    gruppe: "Zitrus", herkunft: "Brasilien, Italien, USA",
    schwerpunkt: "Stimmung, Kinder, Entspannung",
    duft: "süß, fruchtig, warm",
    gewinnung: "Kaltpressung der Fruchtschalen",
    inhalt: "Limonen (über 90 %)",
    text: "Süßes Orangenöl zählt zu den mildesten und beliebtesten Zitrusölen und ist besonders in Familien mit Kindern geschätzt.",
    gesundheit: "Orangenöl gilt in der Aromapraxis als das freundlichste unter den Zitrusölen. Traditionell wird es zur Stimmungsaufhellung, bei innerer Anspannung und als sanftes Einschlafritual für Kinder eingesetzt. Wegen seiner Milde ist es eines der wenigen Öle, die schon in kleinen Mengen im Kinderzimmer verwendet werden – stets in großzügigem Abstand und niedriger Dosierung.",
    anwendungen: [
      ["Gute Laune", "3–4 Tropfen im Diffusor für eine warme, fröhliche Atmosphäre."],
      ["Kinderzimmer", "1 Tropfen im Diffusor in kindersicherem Abstand, maximal 20 Minuten."],
      ["Entspannungsbad", "2 Tropfen mit einem Esslöffel Sahne oder Honig emulgieren und ins Badewasser geben."],
      ["Weihnachtliche Stimmung", "Mit Zimt und Nelke kombiniert für einen festlichen Raumduft."],
      ["Handpflege", "1 Tropfen auf einen Teelöffel Olivenöl für eine pflegende Handmassage am Abend."],
      ["Unruhe bei Erkältung (Kinder ab 3)", "1 Tropfen im Diffusor in kindersicherem Abstand, höchstens 20 Minuten."],
      ["Anspannung vor dem Einschlafen", "2 Tropfen mit Lavendel kombiniert im Diffusor verströmen."],
    ],
    sicherheit: "Wie alle Zitrusöle leicht photosensibilisierend – nach Hautanwendung Sonne meiden. Rasch verbrauchen, da leicht oxidierend.",
  },
  {
    nr: 7, name: "Rosmarin", latin: "Rosmarinus officinalis", img: "rosmarin",
    gruppe: "Kräuter", herkunft: "Mittelmeerraum, Tunesien, Spanien",
    schwerpunkt: "Durchblutung, Muskeln, Gedächtnis",
    duft: "krautig-würzig, kampferartig-frisch",
    gewinnung: "Wasserdampfdestillation des blühenden Krauts",
    inhalt: "1,8-Cineol, Campher, α-Pinen (je nach Chemotyp)",
    text: "Rosmarin gilt seit der Antike als Kraut der Erinnerung und wird traditionell mit geistiger Klarheit und Vitalität verbunden.",
    gesundheit: "Rosmarin wird in der Erfahrungsheilkunde als anregendes, durchblutungsförderndes Öl geführt. Traditionell nutzt man es bei Erschöpfung, zur Unterstützung von Konzentration und Gedächtnis sowie bei verspannter Muskulatur. In der Haarpflege hat Rosmarin eine lange Tradition zur Kräftigung der Kopfhaut. Achten Sie auf den Chemotyp: Cineol-Typ für die Atemwege, Campher-Typ für Muskeln.",
    anwendungen: [
      ["Lernen und Konzentration", "2 Tropfen im Diffusor beim Arbeiten oder Lernen."],
      ["Kopfhaut und Haare", "2 Tropfen auf einen Esslöffel Olivenöl geben, in die Kopfhaut einmassieren, 30 Minuten einwirken lassen, dann auswaschen."],
      ["Verspannte Muskulatur", "3 Tropfen auf einen Esslöffel Olivenöl geben und kräftig einmassieren."],
      ["Morgenritual bei Müdigkeit", "Einen Tropfen in den Handflächen verreiben und tief einatmen."],
      ["Kalte Füße", "2 Tropfen mit Olivenöl verdünnt einmassieren."],
      ["Rücken- und Nackenverspannungen", "3 Tropfen auf einen Esslöffel Olivenöl geben und kräftig einmassieren."],
      ["Kreislaufschwäche am Morgen", "Einen Tropfen in den Handflächen verreiben und tief einatmen, dazu kalt abduschen."],
    ],
    sicherheit: "Nicht in der Schwangerschaft. Bei Epilepsie und Bluthochdruck nur nach ärztlicher Rücksprache. Nicht bei Kindern unter 6 Jahren.",
  },
  {
    nr: 8, name: "Zitronengras", latin: "Cymbopogon citratus", img: "zitronengras",
    gruppe: "Kräuter", herkunft: "Indien, Sri Lanka, Guatemala",
    schwerpunkt: "Insektenschutz, Muskelkater",
    duft: "frisch, zitrusartig, grasig",
    gewinnung: "Wasserdampfdestillation der Blätter",
    inhalt: "Citral (65–85 %), Geraniol, Myrcen",
    text: "Zitronengras verbindet die Frische von Zitrusfrüchten mit einer erdigen Note und ist in Küche wie Aromatherapie zu Hause.",
    gesundheit: "Citral verleiht dem Öl seinen typischen Duft und ist gleichzeitig für die insektenabweisende Wirkung verantwortlich, für die Zitronengras traditionell bekannt ist. In der Aromapraxis wird es außerdem bei Muskelkater und schweren Beinen nach dem Sport geschätzt sowie als klärendes Öl für die Raumluft an warmen Tagen.",
    anwendungen: [
      ["Natürlicher Insektenschutz", "15 Tropfen mit 100 ml Wasser und einem Emulgator in einer Sprühflasche mischen, auf Kleidung sprühen."],
      ["Nach dem Sport", "3 Tropfen auf einen Esslöffel Olivenöl geben und in beanspruchte Muskulatur einmassieren."],
      ["Sommerliche Terrasse", "3 Tropfen im Diffusor an warmen Abenden."],
      ["Yoga und Meditation", "2 Tropfen im Diffusor während der Praxis für Klarheit."],
      ["Schuhfrische", "Einen Tropfen auf ein Wattepad geben und über Nacht in Sportschuhe legen."],
      ["Insektenstiche", "1 Tropfen stark mit Olivenöl verdünnt auf den Stich tupfen."],
      ["Schwere Beine nach langem Stehen", "3 Tropfen auf einen Esslöffel Olivenöl geben und von unten nach oben ausstreichen."],
    ],
    sicherheit: "Kann bei empfindlicher Haut reizen – maximal 1 % verdünnen und vorab einen Patch-Test durchführen. Nicht bei Kindern unter 2 Jahren.",
  },
  {
    nr: 9, name: "Ingwer", latin: "Zingiber officinale", img: "ingwer",
    gruppe: "Wurzeln & Gewürze", herkunft: "Indien, China, Madagaskar",
    schwerpunkt: "Wärme, Übelkeit, Verdauung",
    duft: "warm, würzig-scharf, erdig",
    gewinnung: "Wasserdampfdestillation der getrockneten Wurzelstöcke",
    inhalt: "Zingiberen, β-Sesquiphellandren, Camphen",
    text: "Ingweröl wird aus dem Wurzelstock destilliert und ist bekannt für seinen wärmenden, belebenden Charakter.",
    gesundheit: "Ingwer gehört zu den ältesten Heilpflanzen überhaupt und wird traditionell mit Wärme und einem ruhigen Magen verbunden. In der Aromapraxis nutzt man das Öl bei Reiseunwohlsein durch Inhalation sowie zur wärmenden Massage bei kalten Händen und Füßen. Die Sesquiterpene verleihen ihm einen tief wärmenden, erdenden Charakter.",
    anwendungen: [
      ["Unterwegs und auf Reisen", "Bei Unwohlsein einen Tropfen auf ein Taschentuch geben und mehrmals tief daran riechen."],
      ["Wärmende Massage", "3 Tropfen auf einen Esslöffel Olivenöl bei kalten Händen und Füßen einmassieren."],
      ["Bauchwohlgefühl", "2 Tropfen mit Olivenöl verdünnt sanft im Uhrzeigersinn auf den Bauch auftragen."],
      ["Vor dem Training", "Mit Olivenöl verdünnt zur Erwärmung der Muskulatur einmassieren."],
      ["Herbstliche Raumluft", "Mit Orange und Zimt kombiniert im Diffusor verströmen."],
      ["Reiseübelkeit", "Einen Tropfen auf ein Taschentuch geben und vor und während der Fahrt daran riechen."],
      ["Gelenkbeschwerden bei Kälte", "3 Tropfen auf einen Esslöffel Olivenöl geben und wärmend einmassieren."],
    ],
    sicherheit: "Kann in höherer Konzentration die Haut reizen. Maximal 1 % verdünnen. In der Schwangerschaft nur nach Rücksprache mit der Hebamme.",
  },
  {
    nr: 10, name: "Gewürznelke", latin: "Syzygium aromaticum", img: "nelke",
    gruppe: "Wurzeln & Gewürze", herkunft: "Madagaskar, Indonesien, Sansibar",
    schwerpunkt: "Zahnpflege, Winterduft",
    duft: "warm, würzig-süß, intensiv",
    gewinnung: "Wasserdampfdestillation der getrockneten Blütenknospen",
    inhalt: "Eugenol (75–88 %)",
    text: "Nelkenöl zählt zu den intensivsten ätherischen Ölen überhaupt – wenige Tropfen genügen.",
    gesundheit: "Eugenol ist einer der bekanntesten Naturstoffe der Zahnheilkunde und war lange Bestandteil zahnärztlicher Präparate. Die traditionelle Anwendung des Nelkenöls bei Zahnbeschwerden ist deshalb weit verbreitet. Wegen des hohen Phenolanteils gehört Nelkenöl aber zu den reizstärksten Ölen – es verlangt besondere Zurückhaltung bei der Dosierung.",
    anwendungen: [
      ["Zahnpflege-Tradition", "1 Tropfen auf einen Teelöffel Olivenöl geben, mit einem Wattestäbchen punktuell am Zahnfleisch auftragen – ersetzt keinen Zahnarztbesuch."],
      ["Weihnachtlicher Raumduft", "1 Tropfen mit Orange und Zimt im Diffusor verströmen."],
      ["Mottenschutz", "2 Tropfen auf ein Wattepad geben und in den Kleiderschrank legen."],
      ["Haushaltsreiniger", "5 Tropfen in einem selbstgemachten Reinigungsspray einsetzen."],
      ["Wärmende Wintermassage", "1 Tropfen auf zwei Esslöffel Olivenöl, mit Orange gemischt einmassieren."],
      ["Zahnschmerzen bis zum Zahnarzttermin", "1 Tropfen auf einen Teelöffel Olivenöl geben und mit einem Wattestäbchen auf das Zahnfleisch tupfen."],
      ["Gereiztes Zahnfleisch", "Stark verdünnt punktuell auftragen, gut ausspucken und nicht schlucken."],
    ],
    sicherheit: "Sehr haut- und schleimhautreizend. Maximal 0,5 % verdünnen. Nicht bei Kindern, in Schwangerschaft und Stillzeit sowie bei Blutgerinnungsstörungen.",
  },
  {
    nr: 11, name: "Weihrauch", latin: "Boswellia sacra / carterii", img: "weihrauch",
    gruppe: "Bäume & Harze", herkunft: "Oman, Somalia, Äthiopien",
    schwerpunkt: "Meditation, reife Haut",
    duft: "harzig-warm, leicht zitrisch, erdig",
    gewinnung: "Wasserdampfdestillation des Harzes",
    inhalt: "α-Pinen, Limonen, Boswelliasäuren (im Harz)",
    text: "Weihrauch begleitet Menschen seit Jahrtausenden bei spirituellen Anlässen und gilt als das Öl der inneren Ruhe.",
    gesundheit: "Weihrauch wird in der Aromapraxis vor allem für die Atmung und die Sammlung eingesetzt – tiefes, ruhiges Atmen fällt vielen Menschen mit diesem Duft leichter. In der Hautpflege hat er Tradition bei reifer Haut und zur Pflege verheilter Narben. Die viel diskutierten Boswelliasäuren finden sich übrigens im Harz, nicht im destillierten ätherischen Öl.",
    anwendungen: [
      ["Meditation und Achtsamkeit", "2–3 Tropfen im Diffusor für eine ruhige, geerdete Atmosphäre."],
      ["Bewusste Atemübungen", "Einen Tropfen in den Handflächen verreiben und langsam tief einatmen."],
      ["Pflege reifer Haut", "1 Tropfen auf einen Teelöffel Olivenöl geben und abends ins Gesicht einmassieren."],
      ["Narbenpflege", "Mit Olivenöl verdünnt sanft auf bereits verheilte Narben auftragen."],
      ["Abendritual", "Mit Lavendel kombiniert im Diffusor zum Tagesausklang."],
      ["Verheilende Wunden und Narben", "1 Tropfen mit Olivenöl verdünnt auf die bereits geschlossene Haut auftragen."],
      ["Gelenkbeschwerden", "3 Tropfen auf einen Esslöffel Olivenöl geben und sanft einmassieren."],
    ],
    sicherheit: "Gilt als sehr gut verträglich. Vor der Erstanwendung dennoch Patch-Test durchführen. Auf nachhaltige Herkunft achten – wilde Bestände sind gefährdet.",
  },
  {
    nr: 12, name: "Römische Kamille", latin: "Chamaemelum nobile", img: "kamille",
    gruppe: "Blüten", herkunft: "England, Frankreich",
    schwerpunkt: "Kinder, empfindliche Haut",
    duft: "mild, apfelartig-süß, krautig",
    gewinnung: "Wasserdampfdestillation der Blütenköpfchen",
    inhalt: "Isobutylangelat, Isoamylangelat (Ester über 75 %)",
    text: "Die Römische Kamille ist eines der mildesten ätherischen Öle und besonders für Kinder und empfindliche Haut geeignet.",
    gesundheit: "Der außergewöhnlich hohe Esteranteil macht die Römische Kamille zu einem der sanftesten Öle überhaupt. In der Erfahrungsheilkunde wird sie bei nervöser Unruhe, Einschlafproblemen und gereizter Haut eingesetzt – gerade auch bei Kindern und älteren Menschen. Sie ist damit das Öl der Wahl, wenn andere zu intensiv wären.",
    anwendungen: [
      ["Einschlafhilfe für Kinder", "1 Tropfen im Diffusor in kindersicherem Abstand, 20 Minuten vor dem Zubettgehen."],
      ["Innere Unruhe", "1 Tropfen auf einen Teelöffel Olivenöl geben und aufs Brustbein auftragen, dann bewusst einatmen."],
      ["Gereizte Haut", "1 Tropfen mit Olivenöl verdünnt vorsichtig auftragen."],
      ["Kissenspray", "1 Tropfen mit Wasser und Emulgator mischen und leicht aufs Kopfkissen sprühen."],
      ["Beruhigendes Bad", "2 Tropfen mit Sahne emulgiert ins warme Badewasser geben."],
      ["Juckreiz und gereizte Haut", "1 Tropfen auf einen Esslöffel Olivenöl geben und vorsichtig auftragen."],
      ["Bauchschmerzen bei Kindern ab 6", "1 Tropfen auf zwei Esslöffel Olivenöl geben und sanft im Uhrzeigersinn einmassieren."],
    ],
    sicherheit: "Auch für Kinder ab 3 Jahren in geringer Verdünnung geeignet. Bei Korbblütler-Allergie meiden. In der Schwangerschaft mit Hebamme abklären.",
  },
  {
    nr: 13, name: "Ylang-Ylang", latin: "Cananga odorata", img: "ylang",
    gruppe: "Blüten", herkunft: "Madagaskar, Komoren",
    schwerpunkt: "Anspannung, Haarpflege",
    duft: "schwer, blumig-süß, exotisch",
    gewinnung: "Fraktionierte Wasserdampfdestillation der Blüten",
    inhalt: "Linalool, Germacren D, Benzylacetat",
    text: "Ylang-Ylang gilt als sinnliches Öl und wird traditionell mit Entspannung und emotionalem Gleichgewicht verbunden.",
    gesundheit: "In der Aromapraxis wird Ylang-Ylang bei innerer Anspannung, Herzklopfen aus Nervosität und Stimmungsschwankungen geschätzt. Es gilt als ausgleichendes Öl, das gleichzeitig entspannt und aufhellt. In der Haarpflege hat es Tradition bei trockenem, sprödem Haar. Weniger ist hier deutlich mehr – zu hohe Dosierung kann Kopfschmerzen auslösen.",
    anwendungen: [
      ["Warme Abendatmosphäre", "2 Tropfen im Diffusor für ein einladendes Raumgefühl."],
      ["Emotionale Balance", "Mit Bergamotte kombiniert bei innerer Anspannung im Diffusor verströmen."],
      ["Haarpflege", "2 Tropfen auf einen Esslöffel Olivenöl als Haarkur in die Längen geben, 30 Minuten einwirken lassen."],
      ["Handmassage", "1 Tropfen mit Olivenöl verdünnt sanft in die Hände einmassieren."],
      ["Entspannungsbad", "2 Tropfen mit Emulgator ins Badewasser geben."],
      ["Herzklopfen bei Nervosität", "1 Tropfen im Diffusor oder stark verdünnt auf die Herzgegend auftragen."],
      ["Innere Anspannung am Abend", "Sehr sparsam dosieren – 1 Tropfen genügt, mehr kann Kopfschmerzen auslösen."],
    ],
    sicherheit: "Sparsam dosieren – zu viel kann Kopfschmerzen und Übelkeit auslösen. Bei niedrigem Blutdruck vorsichtig anwenden.",
  },
  {
    nr: 14, name: "Geranie", latin: "Pelargonium graveolens", img: "geranie",
    gruppe: "Blüten", herkunft: "Ägypten, Réunion, China",
    schwerpunkt: "Hautbalance, Stimmung",
    duft: "blumig-rosig, frisch-grün",
    gewinnung: "Wasserdampfdestillation der Blätter",
    inhalt: "Citronellol, Geraniol, Linalool",
    text: "Geranienöl gilt als das Ausgleichs-Öl für Haut und Gemüt und wird oft als preiswerte Alternative zur Rose eingesetzt.",
    gesundheit: "Geranie wird in der Aromapraxis als hormonell ausgleichendes Öl geführt und traditionell in den Wechseljahren und bei zyklusbedingten Stimmungsschwankungen eingesetzt. In der Hautpflege gilt es als ausgleichend für jeden Hauttyp, da es weder stark austrocknet noch beschwert – deshalb ist es Bestandteil vieler Gesichtspflegen.",
    anwendungen: [
      ["Tägliche Hautpflege", "1 Tropfen auf einen Teelöffel Olivenöl geben und als Gesichtsöl auftragen."],
      ["Emotionaler Ausgleich", "2–3 Tropfen im Diffusor bei Stimmungsschwankungen."],
      ["Wechseljahre", "2 Tropfen mit Olivenöl verdünnt auf den Unterbauch auftragen."],
      ["Insektenschutz", "Mit Zitronengras kombiniert als Bestandteil eines Sprays."],
      ["Wellness-Bad", "2 Tropfen mit Emulgator ins warme Badewasser geben."],
      ["Zyklusbedingte Beschwerden", "3 Tropfen auf einen Esslöffel Olivenöl geben und auf den Unterbauch einmassieren."],
      ["Kleine Hautverletzungen", "1 Tropfen mit Olivenöl verdünnt auf den gereinigten Wundrand tupfen."],
    ],
    sicherheit: "Grundsätzlich gut verträglich. In der Schwangerschaft und bei hormonabhängigen Erkrankungen vorher ärztlich abklären.",
  },
  {
    nr: 15, name: "Bergamotte", latin: "Citrus bergamia", img: "bergamotte",
    gruppe: "Zitrus", herkunft: "Italien (Kalabrien)",
    schwerpunkt: "Stimmungstief, Stress",
    duft: "frisch-zitrisch, leicht blumig, elegant",
    gewinnung: "Kaltpressung der Fruchtschalen",
    inhalt: "Limonen, Linalylacetat, Bergapten",
    text: "Bergamotte gibt dem Earl-Grey-Tee seinen Duft und gilt als das stimmungsaufhellendste unter den Zitrusölen.",
    gesundheit: "Bergamotte nimmt eine Sonderstellung ein: Sie wirkt gleichzeitig aufhellend und beruhigend, was sie in der Aromapraxis zum wichtigsten Öl bei gedrückter Stimmung und Stress macht. Traditionell wird sie bei Anspannung, Prüfungsstress und Stimmungstiefs in der dunklen Jahreszeit eingesetzt. Für Hautanwendungen sollten Sie bergaptenfreie (FCF-)Qualität wählen.",
    anwendungen: [
      ["Stimmungsaufhellung", "3 Tropfen im Diffusor am Arbeitsplatz oder im Wohnzimmer."],
      ["Prüfungsstress", "Mit Weihrauch kombiniert im Diffusor für Ruhe bei Konzentration."],
      ["Einschlafritual", "Mit Lavendel kombiniert am Abend im Diffusor verströmen."],
      ["Natürliches Parfum", "3 Tropfen auf 10 ml Olivenöl in einer Rollerflasche als Duftöl."],
      ["Entspannungsbad", "2 Tropfen mit Emulgator ins Badewasser geben."],
      ["Nervöse Magenbeschwerden", "1 Tropfen mit Olivenöl verdünnt sanft auf den Bauch auftragen."],
      ["Winterblues", "3 Tropfen im Diffusor an dunklen Nachmittagen verströmen."],
    ],
    sicherheit: "Stark phototoxisch – nach Hautkontakt mindestens 12 Stunden Sonne und Solarium meiden. Für die Haut bergaptenfreie (FCF-)Qualität wählen.",
  },
  {
    nr: 16, name: "Wacholder", latin: "Juniperus communis", img: "wacholder",
    gruppe: "Bäume & Harze", herkunft: "Kroatien, Albanien, Österreich",
    schwerpunkt: "Entschlackung, Muskeln",
    duft: "frisch, holzig-würzig, leicht harzig",
    gewinnung: "Wasserdampfdestillation der reifen Beerenzapfen",
    inhalt: "α-Pinen, Myrcen, Sabinen",
    text: "Wacholderöl wird aus den Beerenzapfen gewonnen und gilt traditionell als reinigendes, klärendes Öl.",
    gesundheit: "Wacholder wird in der Erfahrungsheilkunde als entschlackendes Öl geführt und traditionell bei Wassereinlagerungen, schweren Beinen und in Entschlackungskuren eingesetzt. In der Sportmassage schätzt man ihn bei verspannter Muskulatur. Wegen der Nierenwirkung ist Zurückhaltung geboten – bei Nierenerkrankungen ist Wacholder tabu.",
    anwendungen: [
      ["Schwere Beine", "3 Tropfen auf einen Esslöffel Olivenöl geben und von unten nach oben ausstreichen."],
      ["Massage nach dem Sport", "Mit Olivenöl verdünnt in verspannte Muskulatur einmassieren."],
      ["Raumreinigung", "3 Tropfen im Diffusor nach Krankheit oder in der kalten Jahreszeit."],
      ["Fußbad", "3 Tropfen in ein warmes Fußbad geben."],
      ["Neuanfang-Ritual", "Mit Zitrone kombiniert im Diffusor bei Jahreswechsel oder Neubeginn."],
      ["Wassereinlagerungen in den Beinen", "3 Tropfen auf einen Esslöffel Olivenöl geben und Richtung Herz ausstreichen."],
      ["Gelenkbeschwerden", "3 Tropfen mit Olivenöl verdünnt vorsichtig einmassieren."],
    ],
    sicherheit: "Nicht in der Schwangerschaft und bei Nierenerkrankungen. Nicht über längere Zeiträume ununterbrochen anwenden.",
  },
  {
    nr: 17, name: "Muskatellersalbei", latin: "Salvia sclarea", img: "muskatellersalbei",
    gruppe: "Blüten", herkunft: "Frankreich, Russland, Bulgarien",
    schwerpunkt: "Frauengesundheit, Zyklus",
    duft: "krautig-nussig, warm, leicht süß",
    gewinnung: "Wasserdampfdestillation des blühenden Krauts",
    inhalt: "Linalylacetat, Linalool, Sclareol",
    text: "Muskatellersalbei gilt als eines der bekanntesten Frauen-Öle der Aromatherapie.",
    gesundheit: "Sclareol besitzt eine östrogenähnliche Molekülstruktur – deshalb wird Muskatellersalbei in der Aromapraxis traditionell bei Zyklusbeschwerden, in den Wechseljahren und bei prämenstrueller Anspannung eingesetzt. Gleichzeitig gilt er als stark entspannendes Öl bei nervöser Erschöpfung. Genau wegen der hormonellen Struktur ist er in Schwangerschaft und bei hormonabhängigen Erkrankungen zu meiden.",
    anwendungen: [
      ["Zyklusbeschwerden", "3 Tropfen auf einen Esslöffel Olivenöl geben und warm auf den Unterbauch einmassieren."],
      ["Wechseljahre", "2 Tropfen im Diffusor oder verdünnt auf die Handgelenke auftragen."],
      ["Entspannung am Abend", "2 Tropfen im Diffusor vor dem Schlafengehen."],
      ["Nackenverspannung", "2 Tropfen mit Olivenöl verdünnt sanft einmassieren."],
      ["Entspannungsbad", "2 Tropfen mit Emulgator ins warme Badewasser geben."],
      ["Menstruationsbeschwerden", "3 Tropfen auf einen Esslöffel Olivenöl geben und warm auf den Unterbauch auftragen."],
      ["Nächtliches Schwitzen in den Wechseljahren", "1 Tropfen im Diffusor am Abend verströmen."],
    ],
    sicherheit: "Nicht in Schwangerschaft und Stillzeit sowie bei hormonabhängigen Erkrankungen. Nicht mit Alkohol kombinieren – verstärkt die Müdigkeit. Nicht vor dem Autofahren.",
  },
  {
    nr: 18, name: "Sandelholz", latin: "Santalum album", img: "sandelholz",
    gruppe: "Bäume & Harze", herkunft: "Indien, Australien",
    schwerpunkt: "Innere Ruhe, Hautpflege",
    duft: "holzig-warm, sanft-süß, cremig",
    gewinnung: "Wasserdampfdestillation des Kernholzes",
    inhalt: "α-Santalol, β-Santalol (über 70 %)",
    text: "Sandelholz zählt zu den kostbarsten ätherischen Ölen der Welt und wird seit Jahrtausenden für Meditation und Hautpflege geschätzt.",
    gesundheit: "Die Santalole geben dem Öl seinen unverwechselbaren Charakter und gelten in der Aromapraxis als tief beruhigend. Sandelholz wird traditionell bei innerer Unruhe, Grübeln und Einschlafproblemen eingesetzt sowie in der Pflege trockener und reifer Haut. In der ayurvedischen Tradition hat es einen festen Platz als kühlendes, sammelndes Öl.",
    anwendungen: [
      ["Tiefe Entspannung", "2 Tropfen im Diffusor beim Meditieren oder vor dem Schlafengehen."],
      ["Pflege reifer Haut", "1 Tropfen auf einen Teelöffel Olivenöl als abendliches Gesichtsöl."],
      ["Gedankenkarussell", "Einen Tropfen in den Handflächen verreiben und langsam einatmen."],
      ["Pflege nach der Rasur", "1 Tropfen mit Olivenöl verdünnt sanft auftragen."],
      ["Yoga und Atemarbeit", "Mit Weihrauch kombiniert im Diffusor während der Praxis."],
      ["Trockener Reizhusten", "2 Tropfen im Diffusor im Schlafzimmer verströmen."],
      ["Erschöpfung mit innerer Unruhe", "1 Tropfen verdünnt auf Brustbein und Handgelenke auftragen."],
    ],
    sicherheit: "Sehr gut verträglich. Auf zertifiziert nachhaltige Herkunft achten (Australien) – indische Wildbestände sind stark gefährdet und geschützt.",
  },
  {
    nr: 19, name: "Zedernholz", latin: "Cedrus atlantica", img: "zedernholz",
    gruppe: "Bäume & Harze", herkunft: "Marokko (Atlasgebirge)",
    schwerpunkt: "Kopfhaut, Erdung, Bindegewebe",
    duft: "warm-holzig, balsamisch, leicht rauchig",
    gewinnung: "Wasserdampfdestillation des Holzes",
    inhalt: "Himachalene, Atlanton, Cedrol",
    text: "Zedernholz ist ein erdendes, kräftigendes Öl mit langer Tradition in der Haar- und Hautpflege.",
    gesundheit: "In der Aromapraxis gilt Zedernholz als das Öl für Struktur und Halt – traditionell eingesetzt bei innerer Zerstreutheit und Grübeln. Besondere Bedeutung hat es in der Kopfhautpflege: Bei fettiger Kopfhaut und dünner werdendem Haar gehört es zu den am häufigsten empfohlenen Ölen. Zudem wird es in der Lymph- und Bindegewebsmassage eingesetzt.",
    anwendungen: [
      ["Kopfhaut und Haarwuchs", "3 Tropfen auf einen Esslöffel Olivenöl geben, in die Kopfhaut einmassieren, 30 Minuten einwirken lassen."],
      ["Bindegewebsmassage", "3 Tropfen mit Olivenöl verdünnt in kreisenden Bewegungen einmassieren."],
      ["Erdung bei Unruhe", "2 Tropfen im Diffusor, besonders am Abend."],
      ["Fettige Haut", "1 Tropfen mit Olivenöl verdünnt punktuell auftragen."],
      ["Mottenschutz", "Wenige Tropfen auf ein Holzstück oder Wattepad in den Kleiderschrank legen."],
      ["Schuppen und juckende Kopfhaut", "3 Tropfen auf einen Esslöffel Olivenöl geben, einmassieren, 30 Minuten einwirken lassen."],
      ["Schwere Beine", "3 Tropfen mit Olivenöl verdünnt von unten nach oben ausstreichen."],
    ],
    sicherheit: "Nicht in der Schwangerschaft. Nicht bei Kindern unter 6 Jahren. Nicht mit Zedernholz aus Virginia (Juniperus virginiana) verwechseln.",
  },
  {
    nr: 20, name: "Grapefruit", latin: "Citrus paradisi", img: "grapefruit",
    gruppe: "Zitrus", herkunft: "USA, Israel, Brasilien",
    schwerpunkt: "Antrieb, Stoffwechsel, Bindegewebe",
    duft: "frisch-herb, spritzig, leicht bitter",
    gewinnung: "Kaltpressung der Fruchtschalen",
    inhalt: "Limonen (über 90 %), Nootkaton",
    text: "Grapefruit ist das anregendste unter den Zitrusölen und ein Klassiker in Wellness- und Figurpflege-Anwendungen.",
    gesundheit: "Grapefruitöl wird in der Aromapraxis traditionell zur Unterstützung des Stoffwechsels und in der Bindegewebspflege eingesetzt – Cellulite-Massageöle enthalten es fast immer. Der Duftstoff Nootkaton gilt als charakteristisch für die anregende Wirkung. Außerdem wird es bei Antriebslosigkeit und Heißhunger-Situationen genutzt.",
    anwendungen: [
      ["Bindegewebs-Massage", "4 Tropfen auf einen Esslöffel Olivenöl geben und mit kreisenden Bewegungen einmassieren."],
      ["Antrieb am Morgen", "3 Tropfen im Diffusor für einen schwungvollen Start."],
      ["Heißhunger-Momente", "Einen Tropfen auf ein Taschentuch geben und bewusst daran riechen."],
      ["Frische Raumluft", "Mit Zitrone kombiniert im Diffusor verströmen."],
      ["Erfrischendes Duschöl", "3 Tropfen auf einen Esslöffel Olivenöl als Duschöl verwenden."],
      ["Wassereinlagerungen", "4 Tropfen auf einen Esslöffel Olivenöl geben und Richtung Herz ausstreichen."],
      ["Erschöpfung und Antriebslosigkeit", "3 Tropfen im Diffusor am Vormittag verströmen."],
    ],
    sicherheit: "Phototoxisch – nach Hautkontakt 12 Stunden Sonne meiden. Wichtig: Grapefruit kann die Wirkung zahlreicher Medikamente beeinflussen – bei regelmäßiger Medikamenteneinnahme ärztlich abklären.",
  },
  {
    nr: 21, name: "Thymian", latin: "Thymus vulgaris", img: "thymian",
    gruppe: "Kräuter", herkunft: "Spanien, Frankreich, Marokko",
    schwerpunkt: "Atemwege, Abwehrkräfte",
    duft: "würzig-krautig, warm, durchdringend",
    gewinnung: "Wasserdampfdestillation des blühenden Krauts",
    inhalt: "Thymol, Carvacrol (Chemotyp Thymol); Linalool (Chemotyp Linalool)",
    text: "Thymian ist eines der kraftvollsten Kräuteröle und in der kalten Jahreszeit kaum zu ersetzen.",
    gesundheit: "Thymian gehört zu den traditionsreichsten Pflanzen für die Atemwege – Thymiantee und Hustensäfte sind seit Generationen bekannt. Das ätherische Öl wird in der Aromapraxis bei festsitzendem Husten und in der Erkältungszeit eingesetzt sowie zur Stärkung in Phasen der Erschöpfung. Wichtig ist der Chemotyp: Thymol ist kraftvoll, aber hautreizend; Linalool ist mild und auch für Kinder geeignet.",
    anwendungen: [
      ["Erkältungszeit", "2 Tropfen (Chemotyp Linalool) im Diffusor verströmen."],
      ["Brusteinreibung", "1 Tropfen auf einen Esslöffel Olivenöl geben und sanft auf die Brust auftragen."],
      ["Erschöpfungsphasen", "Einen Tropfen auf ein Taschentuch geben und tief einatmen."],
      ["Fußbad bei Erkältungsgefühl", "2 Tropfen in ein warmes Fußbad geben."],
      ["Raumluft-Klärung", "Mit Zitrone kombiniert im Diffusor nach Krankheit."],
      ["Festsitzender Husten", "1 Tropfen (Chemotyp Linalool) auf einen Esslöffel Olivenöl geben und auf die Brust einreiben."],
      ["Halskratzen", "2 Tropfen in ein Dampfbad geben und den Dampf mit geschlossenen Augen einatmen."],
    ],
    sicherheit: "Chemotyp Thymol ist stark haut- und schleimhautreizend – maximal 0,5 % verdünnen. Für Kinder und empfindliche Haut ausschließlich Chemotyp Linalool. Nicht in der Schwangerschaft, nicht bei Bluthochdruck.",
  },
  {
    nr: 22, name: "Melisse", latin: "Melissa officinalis", img: "melisse",
    gruppe: "Kräuter", herkunft: "Frankreich, Deutschland, Irland",
    schwerpunkt: "Nervosität, Einschlafen",
    duft: "zitronig-frisch, krautig, fein",
    gewinnung: "Wasserdampfdestillation der Blätter",
    inhalt: "Citral, Citronellal, Geraniol",
    text: "Echte Melisse gehört zu den teuersten Kräuterölen überhaupt – für 1 kg Öl braucht es mehrere Tonnen Pflanzenmaterial.",
    gesundheit: "Melisse ist das klassische Nervenöl der europäischen Klostermedizin und wird traditionell bei nervöser Unruhe, Einschlafproblemen und stressbedingten Magenbeschwerden eingesetzt. In der Aromapraxis gilt sie als besonders geeignet, wenn Anspannung sich körperlich äußert – etwa durch Herzklopfen oder einen flauen Magen. Achtung beim Kauf: Vieles, was als Melissenöl verkauft wird, ist billigeres Zitronengras.",
    anwendungen: [
      ["Nervöse Unruhe", "1 Tropfen im Diffusor oder verdünnt auf die Handgelenke auftragen."],
      ["Einschlafen", "1 Tropfen auf einen Teelöffel Olivenöl geben und aufs Brustbein auftragen."],
      ["Flauer Magen bei Stress", "1 Tropfen mit Olivenöl verdünnt sanft auf den Bauch auftragen."],
      ["Innere Anspannung", "Einen Tropfen auf ein Taschentuch geben und bewusst atmen."],
      ["Lippenpflege-Tradition", "1 Tropfen auf einen Teelöffel Olivenöl geben und punktuell auftragen."],
      ["Lippenbläschen", "1 Tropfen auf einen Teelöffel Olivenöl geben und beim ersten Kribbeln punktuell auftragen."],
      ["Nervöse Magenbeschwerden", "1 Tropfen mit Olivenöl verdünnt sanft auf den Bauch auftragen."],
    ],
    sicherheit: "Sehr sparsam dosieren, kann die Haut reizen (maximal 0,5 %). Beim Kauf auf Melissa officinalis achten – nicht auf Indian Melissa (Zitronengras).",
  },
  {
    nr: 23, name: "Zimt", latin: "Cinnamomum verum", img: "zimt",
    gruppe: "Wurzeln & Gewürze", herkunft: "Sri Lanka, Madagaskar",
    schwerpunkt: "Wärme, Kreislauf, Winter",
    duft: "warm, süß-würzig, intensiv",
    gewinnung: "Wasserdampfdestillation der Rinde oder Blätter",
    inhalt: "Zimtaldehyd (Rinde); Eugenol (Blatt)",
    text: "Zimtöl gehört zu den wärmendsten Ölen überhaupt und ist der Inbegriff winterlicher Gemütlichkeit.",
    gesundheit: "Zimt wird in der Erfahrungsheilkunde als wärmendes, kreislaufanregendes Öl geführt und traditionell bei Frösteln, kalten Extremitäten und Antriebsschwäche in der dunklen Jahreszeit eingesetzt. Entscheidend ist die Unterscheidung: Zimtrindenöl ist extrem hautreizend und sollte nur im Diffusor verwendet werden, Zimtblattöl ist deutlich milder.",
    anwendungen: [
      ["Winterlicher Raumduft", "1 Tropfen mit Orange und Nelke im Diffusor verströmen."],
      ["Wärmende Fußmassage", "1 Tropfen Zimtblattöl auf zwei Esslöffel Olivenöl geben und einmassieren."],
      ["Antriebslosigkeit", "1 Tropfen im Diffusor kombiniert mit Grapefruit."],
      ["Gemütliche Atmosphäre", "1 Tropfen auf einen Tonstein oder Duftring geben."],
      ["Winterbad", "1 Tropfen mit reichlich Sahne emulgiert ins Badewasser geben."],
      ["Frösteln bei beginnender Erkältung", "1 Tropfen Zimtblattöl auf zwei Esslöffel Olivenöl geben und die Füße einreiben."],
      ["Kalte Hände und Füße", "1 Tropfen Zimtblattöl stark verdünnt einmassieren."],
    ],
    sicherheit: "Zimtrindenöl ist stark haut- und schleimhautreizend – nur zur Raumbeduftung. Für die Haut ausschließlich Zimtblattöl, maximal 0,5 %. Nicht bei Kindern, in Schwangerschaft und Stillzeit.",
  },
  {
    nr: 24, name: "Fenchel", latin: "Foeniculum vulgare", img: "fenchel",
    gruppe: "Wurzeln & Gewürze", herkunft: "Ägypten, Ungarn, Frankreich",
    schwerpunkt: "Verdauung, Blähungen",
    duft: "süßlich-anisartig, würzig",
    gewinnung: "Wasserdampfdestillation der reifen Samen",
    inhalt: "trans-Anethol (60–80 %), Fenchon",
    text: "Fenchel ist das klassische Verdauungsöl und aus Baby- und Kindertees seit Generationen bekannt.",
    gesundheit: "Fenchel gehört zu den bestuntersuchten Pflanzen für den Magen-Darm-Bereich. Das ätherische Öl wird in der Aromapraxis traditionell bei Blähungen, Völlegefühl und Krämpfen im Bauchraum eingesetzt – meist als sanfte Bauchmassage. Anethol besitzt zudem eine östrogenähnliche Struktur, weshalb Fenchel traditionell auch in der Stillzeit Verwendung findet, dies aber ärztlich abgeklärt werden sollte.",
    anwendungen: [
      ["Völlegefühl nach dem Essen", "2 Tropfen auf einen Esslöffel Olivenöl geben und im Uhrzeigersinn auf den Bauch einmassieren."],
      ["Blähbauch", "1 Tropfen mit Olivenöl verdünnt sanft einmassieren."],
      ["Bauchwohl für Kinder ab 6", "1 Tropfen auf zwei Esslöffel Olivenöl stark verdünnt auftragen."],
      ["Entspannter Bauch am Abend", "1 Tropfen mit Römischer Kamille kombiniert als Massageöl."],
      ["Warme Bauchkompresse", "2 Tropfen mit Olivenöl auf ein warmes Tuch geben und auflegen."],
      ["Blähungen und Bauchkrämpfe", "2 Tropfen auf einen Esslöffel Olivenöl geben und im Uhrzeigersinn einmassieren."],
      ["Husten mit zähem Schleim", "1 Tropfen auf einen Esslöffel Olivenöl geben und auf die Brust auftragen."],
    ],
    sicherheit: "Nicht in der Schwangerschaft, nicht bei Epilepsie, nicht bei hormonabhängigen Erkrankungen. Nicht bei Kindern unter 6 Jahren. Sparsam dosieren.",
  },
  {
    nr: 25, name: "Patchouli", latin: "Pogostemon cablin", img: "patchouli",
    gruppe: "Kräuter", herkunft: "Indonesien, Indien",
    schwerpunkt: "Haut, Erdung, Narbenpflege",
    duft: "erdig-holzig, schwer, leicht süßlich",
    gewinnung: "Wasserdampfdestillation der fermentierten Blätter",
    inhalt: "Patchoulol, α-Bulnesen, α-Guaien",
    text: "Patchouli ist eines der wenigen Öle, das mit der Zeit besser wird – gut gelagert reift es über Jahre.",
    gesundheit: "In der Aromapraxis gilt Patchouli als stark erdendes Öl, das bei Grübeln, Nervosität und dem Gefühl innerer Zerstreutheit eingesetzt wird. In der Hautpflege hat es lange Tradition bei rissiger, entzündeter und reifer Haut sowie in der Narbenpflege. Die Sesquiterpene machen es zu einem der hautfreundlichsten Öle überhaupt.",
    anwendungen: [
      ["Rissige und trockene Haut", "2 Tropfen auf einen Esslöffel Olivenöl geben und auftragen."],
      ["Erdung bei Grübeln", "2 Tropfen im Diffusor, besonders abends."],
      ["Narbenpflege", "1 Tropfen mit Olivenöl verdünnt auf verheilte Narben auftragen."],
      ["Fußpflege bei rissiger Haut", "3 Tropfen auf einen Esslöffel Olivenöl als Fußbalsam."],
      ["Natürliches Parfum", "2 Tropfen auf 10 ml Olivenöl in einer Rollerflasche."],
      ["Juckende, schuppende Haut", "2 Tropfen auf einen Esslöffel Olivenöl geben und auftragen."],
      ["Bereits verschlossene kleine Wunden", "1 Tropfen mit Olivenöl verdünnt auf den Wundrand tupfen."],
    ],
    sicherheit: "Sehr gut hautverträglich. In hoher Dosierung stark sedierend – sparsam einsetzen. In der Schwangerschaft vorher abklären.",
  },
  {
    nr: 26, name: "Vetiver", latin: "Chrysopogon zizanioides", img: "vetiver",
    gruppe: "Bäume & Harze", herkunft: "Haiti, Java, Indien",
    schwerpunkt: "Tiefenentspannung, Schlaf",
    duft: "erdig, rauchig-holzig, sehr schwer",
    gewinnung: "Wasserdampfdestillation der Wurzeln",
    inhalt: "Vetiverol, Vetivon, Khusimol",
    text: "Vetiver wird aus den Wurzeln gewonnen und ist das erdendste Öl der gesamten Aromatherapie.",
    gesundheit: "Vetiver trägt den Beinamen Öl der Ruhe und wird in der Aromapraxis bei starker innerer Unruhe, Erschöpfungszuständen und hartnäckigen Einschlafproblemen eingesetzt. Es gilt als eines der wenigen Öle, die auch bei ausgeprägtem Gedankenkreisen noch greifen. In Indien werden aus den Wurzeln traditionell kühlende Matten geflochten.",
    anwendungen: [
      ["Hartnäckige Einschlafprobleme", "1 Tropfen im Diffusor oder verdünnt auf die Fußsohlen auftragen."],
      ["Tiefe Erschöpfung", "1 Tropfen auf einen Teelöffel Olivenöl geben und in den Nacken einmassieren."],
      ["Gedankenkreisen", "Einen Tropfen in den Handflächen verreiben und langsam einatmen."],
      ["Erdende Fußmassage", "2 Tropfen auf einen Esslöffel Olivenöl geben und die Füße massieren."],
      ["Meditation", "1 Tropfen mit Weihrauch kombiniert im Diffusor."],
      ["Erschöpfung nach Krankheit", "1 Tropfen auf einen Teelöffel Olivenöl geben und in Nacken und Fußsohlen einmassieren."],
      ["Nächtliches Grübeln", "1 Tropfen im Diffusor, spätestens eine Stunde vor dem Schlafengehen."],
    ],
    sicherheit: "Sehr gut verträglich, aber stark sedierend – nicht vor dem Autofahren. Sehr sparsam dosieren, der Duft ist äußerst intensiv und haftet lange.",
  },
  {
    nr: 27, name: "Rose", latin: "Rosa damascena", img: "rose",
    gruppe: "Blüten", herkunft: "Bulgarien (Rosental), Türkei",
    schwerpunkt: "Reife Haut, emotionale Balance",
    duft: "blumig-süß, tief, unverwechselbar",
    gewinnung: "Wasserdampfdestillation der Blütenblätter",
    inhalt: "Citronellol, Geraniol, Nerol, Phenylethanol",
    text: "Rosenöl ist das kostbarste ätherische Öl der Welt – für einen einzigen Milliliter werden rund 4.000 Blüten benötigt.",
    gesundheit: "Rose gilt in der Aromapraxis als das Öl für Herz und Seele und wird traditionell bei Trauer, Kummer und emotionaler Erschöpfung eingesetzt. In der Hautpflege gehört sie zur absoluten Spitzenklasse: Bei reifer, trockener und empfindlicher Haut ist sie seit Jahrhunderten das Mittel der Wahl. Wegen des Preises wird oft mit Geranie gestreckt – achten Sie auf die Herkunftsangabe.",
    anwendungen: [
      ["Pflege reifer Haut", "1 Tropfen auf einen Esslöffel Olivenöl geben und abends ins Gesicht einmassieren."],
      ["Trauer und Kummer", "1 Tropfen im Diffusor oder auf ein Taschentuch geben."],
      ["Emotionale Erschöpfung", "1 Tropfen verdünnt auf die Herzgegend auftragen."],
      ["Kostbares Gesichtsöl", "2 Tropfen auf 30 ml Olivenöl als tägliche Pflege."],
      ["Besondere Anlässe", "1 Tropfen als natürliches Parfum auf die Handgelenke."],
      ["Empfindliche, gereizte Haut", "1 Tropfen auf einen Esslöffel Olivenöl geben und sanft auftragen."],
      ["Beschwerden in den Wechseljahren", "1 Tropfen im Diffusor oder verdünnt auf die Handgelenke auftragen."],
    ],
    sicherheit: "Sehr gut verträglich. In der Schwangerschaft erst ab dem zweiten Drittel und nach Rücksprache. Auf echtes Rosa damascena achten – Fälschungen sind verbreitet.",
  },
  {
    nr: 28, name: "Jasmin", latin: "Jasminum grandiflorum", img: "jasmin",
    gruppe: "Blüten", herkunft: "Indien, Ägypten, Marokko",
    schwerpunkt: "Stimmung, Selbstvertrauen",
    duft: "intensiv blumig, süß-narkotisch, warm",
    gewinnung: "Extraktion (Absolue) – die Blüten sind zu empfindlich für Destillation",
    inhalt: "Benzylacetat, Linalool, Indol, Jasmon",
    text: "Jasmin wird als König der Nachtblüten bezeichnet und ausschließlich nachts von Hand gepflückt, wenn der Duft am stärksten ist.",
    gesundheit: "In der Aromapraxis gilt Jasmin als stimmungshebendes und stärkendes Öl, das traditionell bei Antriebslosigkeit, Selbstzweifeln und gedrückter Stimmung eingesetzt wird. Anders als die meisten beruhigenden Blütenöle wirkt Jasmin eher aufrichtend. In der Hautpflege wird er bei trockener und empfindlicher Haut geschätzt.",
    anwendungen: [
      ["Gedrückte Stimmung", "1 Tropfen im Diffusor oder verdünnt auf die Handgelenke."],
      ["Selbstvertrauen stärken", "1 Tropfen auf einen Teelöffel Olivenöl geben und vor wichtigen Terminen auftragen."],
      ["Trockene Haut", "1 Tropfen auf einen Esslöffel Olivenöl als Pflegeöl."],
      ["Sinnliche Atmosphäre", "1 Tropfen im Diffusor, mit Sandelholz kombiniert."],
      ["Natürliches Parfum", "2 Tropfen auf 10 ml Olivenöl in einer Rollerflasche."],
      ["Erschöpfung und Antriebslosigkeit", "1 Tropfen im Diffusor am Vormittag verströmen."],
      ["Trockene, spannende Haut", "1 Tropfen auf einen Esslöffel Olivenöl als Pflegeöl auftragen."],
    ],
    sicherheit: "Als Absolue lösungsmittelextrahiert – nicht für die innerliche Anwendung. Sehr sparsam dosieren. Nicht in der Schwangerschaft vor der Geburt.",
  },
  {
    nr: 29, name: "Kiefer", latin: "Pinus sylvestris", img: "kiefer",
    gruppe: "Bäume & Harze", herkunft: "Österreich, Skandinavien, Russland",
    schwerpunkt: "Atemwege, Erschöpfung",
    duft: "frisch-harzig, waldig, klar",
    gewinnung: "Wasserdampfdestillation der Nadeln und Zweige",
    inhalt: "α-Pinen, β-Pinen, Limonen",
    text: "Kiefernöl riecht nach Winterwald und gehört zu den klassischen Ölen für Atemwege und Sauna.",
    gesundheit: "Kiefer wird in der Erfahrungsheilkunde als atemwegsbefreiendes und kräftigendes Öl geführt. Traditionell kommt es bei Erkältungsgefühl, Verschleimung und in der Rekonvaleszenz zum Einsatz. Der hohe Pinen-Anteil gilt in der Aromapraxis als Grund für die klärende Wirkung auf die Atemwege. Zusätzlich wird Kiefer bei Erschöpfung und Antriebsschwäche genutzt.",
    anwendungen: [
      ["Freies Atmen", "3 Tropfen im Diffusor in der Erkältungszeit verströmen."],
      ["Brust- und Rückeneinreibung", "2 Tropfen auf einen Esslöffel Olivenöl geben und einmassieren."],
      ["Saunaaufguss", "2 Tropfen mit dem Aufgusswasser mischen."],
      ["Erschöpfung", "Einen Tropfen auf ein Taschentuch geben und tief einatmen."],
      ["Muskelkater", "3 Tropfen mit Olivenöl verdünnt einmassieren."],
      ["Husten und Verschleimung", "2 Tropfen auf einen Esslöffel Olivenöl geben und Brust und Rücken einreiben."],
      ["Muskelkater und Rückenverspannung", "3 Tropfen mit Olivenöl verdünnt kräftig einmassieren."],
    ],
    sicherheit: "Nicht bei Asthma und Keuchhusten. Nicht bei Kindern unter 6 Jahren. Oxidiertes Öl reizt die Haut – kühl lagern und binnen 12 Monaten verbrauchen.",
  },
  {
    nr: 30, name: "Myrrhe", latin: "Commiphora myrrha", img: "myrrhe",
    gruppe: "Bäume & Harze", herkunft: "Somalia, Äthiopien, Jemen",
    schwerpunkt: "Mund & Zahnfleisch, Wundpflege",
    duft: "warm-balsamisch, herb-bitter, rauchig",
    gewinnung: "Wasserdampfdestillation des Harzes",
    inhalt: "Furanoeudesma-1,3-dien, Curzeren, Lindestren",
    text: "Myrrhe zählt neben Weihrauch zu den ältesten Heil- und Ritualharzen der Menschheit.",
    gesundheit: "Myrrhe hat eine besonders lange Tradition in der Mund- und Zahnpflege – Myrrhentinktur ist bis heute in Apotheken erhältlich und wird bei gereiztem Zahnfleisch eingesetzt. In der Hautpflege gilt Myrrhe als das Öl für schlecht heilende, rissige Haut. Zusätzlich wird sie in der Aromapraxis für Sammlung und Ruhe genutzt, ähnlich wie Weihrauch, aber erdiger.",
    anwendungen: [
      ["Zahnfleischpflege", "1 Tropfen auf einen Teelöffel Olivenöl geben und mit dem Finger sanft einmassieren, nicht schlucken."],
      ["Rissige Haut an Händen und Füßen", "2 Tropfen auf einen Esslöffel Olivenöl geben und auftragen."],
      ["Pflege verheilter Wunden", "1 Tropfen mit Olivenöl verdünnt sanft auftragen."],
      ["Meditation", "2 Tropfen im Diffusor, mit Weihrauch kombiniert."],
      ["Lippenpflege bei Trockenheit", "1 Tropfen auf einen Teelöffel Olivenöl geben, punktuell auftragen."],
      ["Kleine Wunden im Mundraum", "1 Tropfen auf einen Teelöffel Olivenöl geben, punktuell auftragen, nicht schlucken."],
      ["Rissige, schlecht heilende Hautstellen", "2 Tropfen auf einen Esslöffel Olivenöl geben und mehrmals täglich auftragen."],
    ],
    sicherheit: "Nicht in der Schwangerschaft. Bei Schilddrüsenerkrankungen und Diabetes vorher ärztlich abklären. Nicht innerlich einnehmen.",
  },
];
